Fix unzip of config files and incorrect arg name in docker-compose
markusweigelt/kitodo-production-docker pull request #8
Opened 2022-05-31 08:36 UTC by SvenMarcus

2022-05-31 12:50 UTC, SvenMarcus commented
The last commit also fixes a bug with the `OCRD_MANAGER_IP` lookup in `startup.sh` by executing the command in a sub shell

2022-06-02 12:21 UTC, markusweigelt approved these changes

2022-06-02 12:21 UTC, markusweigelt commented on kitodo/Dockerfile
For this case i want to use a seperate build variable so i changed dir name to more general .

2022-06-02 12:21 UTC, markusweigelt commented on kitodo/startup.sh
> +	OCRD_MANAGER_IP=$(nslookup $OCRD_MANAGER_HOST | grep 'Address\:' | awk 'NR==2 {print $2}')
Interesting for me to know: why is it necessary to use a subshell here. We are not running into a "race problem" here?

2022-06-03 08:25 UTC, markusweigelt requested changes
After the tiny improvements i will rebased and merge this.

2022-06-03 08:25 UTC, markusweigelt commented on .gitignore
> +**/config_modules
Please add the newline.

2022-06-03 11:41 UTC, markusweigelt approved these changes

2022-06-03 11:41 UTC, merged